### ISSUE TITLE
Fill Fields only fills the first password field

### ISSUE THREAD

**Issue by breyed** [passwordmaker/chrome-passwordmaker#141]
Clicking the Fill Fields button on the extension button popup window only causes the first password field to be filled in. If there are two (to guard against mistyping), the second field remains empty.

**Comment by heavensrevenge** [comment]
I'm curious @breyed, what device are you getting the bad performance on? Is it a low powered/mobile ARM device?

**Comment by breyed** [comment]
The PC running Chrome is a Lenovo Yoga 2 Pro with an Intel Core i7 at 8 GB RAM, so it's definitely not underpowered. I tried again, and currently the only lag I see is Chrome's animation delay to drop down the toolbar button, which is annoyingly slow at about 1 second each time.

What if <kbd>Alt+Z</kbd>, instead of dropping down the Password Maker toolbar menu, immediately populated the password in the first/next field? Hitting <kbd>Alt+Z,Alt+Z</kbd> to populate two fields would be quick and convenient.

**Comment by heavensrevenge** [comment]
Mind if you right clicked the PasswordMaker Pro toolbar icon and select "Inspect Popup", then once the little extension popup is open press<kbd>F5</kbd> to reload the extension in place without the popup disappearing. Then once it has select the "Network" tab and let me see your load time waterfall. 
Mine looks like this:
![mywf](https://cloud.githubusercontent.com/assets/9080/6717132/0b213764-cd70-11e4-9ce1-15e78b6d54ec.PNG)
I am very curious whats causing your lag.

Also I've been experimenting with adding an asynchronous "localstorage" access library so I make sure all disk accesses are async(non-blocking I/O) instead of sync(blocking I/O) which is where I suspect is/was causing such a big slowdown for you.

**Comment by breyed** [comment]
My waterfall timing was similar. F5 refresh is quick; since the popup is already open, there is no animation delay. I think the animation is dictated by Chrome, not PasswordMaker. Other toolbar extensions, such as Toggl's, animate similarly. IIRC, sometimes, PasswordMaker does have a tiny bit of extra jitter, likely from I/O, but it's small and doesn't reproduce, since the disk access is cached by the second time through.

**Comment by MrTact** [comment]
I have recently had a thought about this.

What if we highlight the field that will be filled in in some way, and then if we detect more than one available field we don't auto-close the popup. You can still close it by hitting ESC if you don't need to fill the second field, so that flow should still be fairly quick.

**Comment by breyed** [comment]
@MrTact Excellent suggestion, IMHO.
