### ISSUE TITLE
Sync password is only security through obscurity

### ISSUE THREAD

**Issue by multiwebinc** [passwordmaker/chrome-passwordmaker#143]
Just as the title says, the sync password can easily be circumvented and is therefore only security through obscurity.

Steps to reproduce:

1. Disable syncing
2. Bring up Chrome's console
3. Click on resources > Local Storage > chrome-extension://... > sync_profiles
4. Change false to true
5. Refresh the page, and voila! All your accounts are there.

Either this should actually encrypt the settings properly or it should be removed.

**Comment by heavensrevenge** [comment]
Hmm well you seem to be correct, I do need to fix this... I definitely did not intend it to be "obscurity" as I was just unaware of this behavior so yes thank you for bringing this to my attention!

**Comment by heavensrevenge** [comment]
OK it's fixed, when clearing that check box I deleted the locally stored sync_profiles_password which was allowing the sync_profiles data to be decrypted as you say... since that sync_profiles data is already encrypted but I sadly didn't delete the cached/stored password/key when disabling that check box.
If you're a js dev, add "localStorage.removeItem("sync_profiles_password");" to line 299 in the updateSyncProfiles() function in options.js if you'd like to confirm this fixes the behavior and correctly secures things.

**Comment by multiwebinc** [comment]
I'm glad I could help. I actually found it because I am thinking of implementing something similar in another extension and I wanted to know  how you accomplished it. 

I tried putting the line of code you had previously and Chrome reports the extension as being corrupted, and if I try to load an unpacked extension it says there's no manifest file, so I guess I can't help you...

**Comment by heavensrevenge** [comment]
Hmm... the extension cant be corrupted by just that lol, there is indeed a manifest.json and be sure you add the folder containing the manifest.json file to install from a folder/local git repo but you could always pull my git repo and work from there.  But modifying the actual code where your chrome profile stores extension code SHOULD work, make sure your using the DEV version of chrome to be safe for development though in case.
You could also just manually delete that localStorage key/value to get the same effect.

**Comment by multiwebinc** [comment]
Yep, removing the entry did it. Actually now I'm unable to retrieve the entries at all even after entering the correct password.

Anyway, I was wondering, how does the sync profiles password work? It looks like you are hashing it, so how do you decrypt the chrome.storage with a password obtained from a hash?

**Comment by heavensrevenge** [comment]
The sync profiles password is actually created using PBKDF2 with 1000 iterations and stored/compared to what's stored, but seeing this is what made me edit my previous comment and mention I should try and redesign this since sync is a little tricky and Google sets sync quotas per hour and debugging sync bugs takes time because of their sync data quota. The sync functionality was not made by me initially but I did add a lot of security to it.

**Comment by multiwebinc** [comment]
Wow hourly sync quotas. I guess they don't have the bandwidth... Poor Google.

**Comment by heavensrevenge** [comment]
The reason fixing this is tricky is because of the legacy and simple Settings.syncPasswordOk variable that is checked.  I am working on it and thinking of how to do it but I am open to contribution and you can by all means help me add features and whistles to this so it suits your needs :) I do hope my code is nice and clean to read to help you learn :)

**Comment by heavensrevenge** [comment]
Also I must mention that this does't need to be super secure, since it's only profile data and it's all useless unless they have your master password to use the profile settings correctly to generate the correct password, also no matter what if you alter enough code in any project it wont be secure since you can just alter it to do anything you want so I can only try and make it have as much correct behavior as possible.
This data is apparently encrypted on Google's servers but I also wanted to make sure Google couldn't see the data we give them in plain text like what profile data used to be synchronized as before I added some security to it.
Would you like trying out a test version I make? As I have changed things and you can try it out before I push to the Chrome Web Store if you were interested to try it out.

**Comment by multiwebinc** [comment]
I don't have that much time right now to actually contribute code, but I could test it for you. I am currently working on several other projects, so my extra time is pretty limited. And to be honest, I don't actually use passwordmaker anymore. I just found it a bit tedious how so many sites impose ridiculous rules on passwords and I had so many different profiles to manage that that I decided to switch to keepass. I can also store other things there too (like SSH keys, credit cards numbers, etc), not just passwords, so I'm happy with it.

**Comment by heavensrevenge** [comment]
Hmm, was there any certain specific aspects of profile management that sucked that I can improve on so it wouldn't be so tedious? A tad off topic sure but I'm all for suggestions to make profile management better.

**Comment by heavensrevenge** [comment]
6b465d2b3585a7271e757669eb9897e5e5d54d01 should fix the way you worked around that sync setting, feel free to give it a try and verify, I'm off to snowboard in Jasper in the Rocky Mountains today :D

**Comment by multiwebinc** [comment]
> Hmm, was there any specific aspects of profile management that sucked that I can improve on so it wouldn't have been so tedious?

I haven't used passwordmaker for about a year now, but if I remember correctly, my main problem was mainly syncing it between multiple browsers and multiple computers whereas with keepass I have my single passwords file that I add to my sync service of choice and I don't have to worry trying to export the file from Chrome and then import it into Firefox, etc. The actual profile management itself was pretty good. I don't know if it would be possible, but maybe if you could have an option use a specific file at a user-specified location for the preferences instead of localStorage (or chrome.storage) that would make it a bit more portable. Then all I have to do is sync that one file and not have to worry about it between browsers.

P.S. have fun snowboarding!

**Comment by heavensrevenge** [comment]
I'm still alive :) So @multiwebinc did you by chance try out my latest code to verify if the issue has been fixed and addressed?  Sadly it was overkill trying to use PBKDF2 for the sync password since salts messed/complicates things when trying to have 0 leakage of data to be used against the encrypted data so a sha256 hash works quite nicely even thought its simple.

**Comment by heavensrevenge** [comment]
Any update @multiwebinc ? I'd really like to push the new code to everyone if you also consider this flaw closed.

**Comment by multiwebinc** [comment]
I'm sorry, but I have just been really busy. Unfortunately I was still able to reproduce it. Here's how, step by step:

- (probably optional) Open up a new profile, or else delete the sync data, and then delete all the localStorage values. Just to start fresh and eliminate any sort of caching issues or whatnot.
- (probably optional) Refresh for good measure
- Add a master password and when sync is enabled, add a few accounts
- Turn syncing off
- Remove all of your accounts (except default, which cannot be removed)
- Click on resources > Local Storage > chrome-extension://... > sync_profiles and change false to true
- Refresh

All of the accounts I had deleted with sync off showed up again without entering a master password.

**Comment by multiwebinc** [comment]
Wait, disregard that last comment for a minute. I was using the wrong version :P

**Comment by multiwebinc** [comment]
OK, I tested it and I am unable to reproduce the error, however, there is one slight thing I would change. If someone manually changes the value of `sync_profiles` to `true`, and it is unable to decrypt the saved data, I would have the app change it back to `false` because visually it appears like it is syncing the data. When you go to the General Options tab, "Sync Profiles Between Computers" is checked.

Of course, this probably is not going to affect anything except for people purposely trying to hack things, but you never know if down the road you introduce some bug that causes the value to be changed to "true" but there was actually an error with the decryption. Know what I mean?

I would say it is ready for pushing right now, though. I hope this helped.

**Comment by heavensrevenge** [comment]
Finally pushed this out in v0.8.1
