### ISSUE TITLE
Leet level changes.

### ISSUE THREAD

**Issue by GAZ082** [passwordmaker/chrome-passwordmaker#144]
I found that, by unknown reasons, the leet level diminishes. I notice this when the password generated is wrong, so i have to go to option and restore leet level to the original one.

**Comment by heavensrevenge** [comment]
That's pretty weird... do you have any deterministic way to reproduce this issue??  Any certain site or possibly is your sync settings getting pulled back on to your local comp and over-writing your local settings?  I've never seen how in the world it could just automatically change the l33t level.  I'll look into it but I'm flying blind here on this issue and it sounds super weird.

**Comment by heavensrevenge** [comment]
Also, do you know how many levels the l33t level change by? Only +-1 or does it jump multiple levels?

**Comment by GAZ082** [comment]
Only on 1 step decrements. In the Android app (by James D Stapleton) it does every time you access the profile. So annoying.

**Comment by heavensrevenge** [comment]
So... it only happened once during the upgrade @GAZ082?
That may just be from me fixing an inconsistency/bug his old version had with the Firefox version https://github.com/passwordmaker/chrome-passwordmaker/commit/3707789452c0d290975446ea982476e09b847626#diff-fe531dcac028098c764e114b1f06a873R98 It may not be a bug in itself but it may be an effect of me fixing that bug showeing itself while doing the upgrade.  That value should never be able to change without you telling it to in normal circumstance.

Try it a bit more to see if it ever happens automatically again.
I hope you like all the stuff I've added and fixed from the old version :)

@tasermonkey you do have a bug concerning the l33t level in your android client.  Every time a profile is viewed which has a l33t level specified, the profile decreases it's value by 1 every time until it reaches level 1 lol.

**Comment by heavensrevenge** [comment]
So has the l33t level ever changed again? Or was it a one time occurrence?

**Comment by heavensrevenge** [comment]
Ok well for now I'll close this issue since it was a one time thing, I really hate that I was't able to just update/continue the old extension then I could at least put a version check and upgrade warning or automatically migrate settings but since mine is technically a different extension according to the Chrome Web Store I cant do any version checks or version migration based on the exported data since its very generic xml(rdf) data..
I'll see if I'd be able to ever add a version # to the exported data that doesn't conflict with all other PasswordMaker import functionality.
This bug... really bugs me lol I'll mention something here if I can find out a way to fix this.

**Comment by GAZ082** [comment]
Did not have this issue again, perhaps was me. If happens again, will report here!
