### ISSUE TITLE
Passwordmaker doesn't show up when website uses separate login browser window

### ISSUE THREAD

**Issue by gwillegers** [passwordmaker/chrome-passwordmaker#169]
One of the websites I visit, has a login form that shows up in a separate browser window. This window does not contain any menu or button bar. There is no chrome-passwordmaker button.

When I press alt-Z, in Chrome nothing happens. In Firefox the passwordmaker popup flashes right below the login window (with the triangle at the top of the popup pointing to the center of the login window).

There is no way I can login here, using chrome-passwordmaker. In Firefox I can login using the original Passwordmaker.org (Eric Jung's XUL version).

**Comment by heavensrevenge** [comment]
What site are you using so I can use it as a test case?

**Comment by gwillegers** [comment]
The site is nl.hardware.info. It has English versions at us.hardware.info and uk.hardware.info. They show the same behaviour.

**Comment by heavensrevenge** [comment]
I at least have a simple/short term solution for you while using Chrome, right click the title bar of the login window and select "Show as Tab" which gives you the login popup for logging in.  On FF... I'm not sure yet other than just using the URL directly "https://hwiconnect.net/connect/" to navigate to for logging in instead of having it be popped up upon trying to login.

**Comment by heavensrevenge** [comment]
Is this still an issue if you use the "Show as Tab" option in Chrome?

**Comment by gwillegers** [comment]
Unfortunately there is no such option. I tried it at work today. There I saw the option. I think this is an option that is only in the Windows version of Chrome. At home I use Linux, so I can't use this workaround.

**Comment by gwillegers** [comment]
Works great! Thanks for the tip.
