### ISSUE TITLE
Removed from stores?

### ISSUE THREAD

**Issue by BigBlueHat** [passwordmaker/chrome-passwordmaker#183]
Chrome and Edge have both just disabled PasswordMaker Pro for me per "policy" and with claims of "malware." 😞 

Here's Chrome's message from the Extensions screen:
![image](https://user-images.githubusercontent.com/43209/119713030-45e04c80-be2f-11eb-8121-ae53ebb29626.png)

And here's Edge's:
![image](https://user-images.githubusercontent.com/43209/119713111-5c86a380-be2f-11eb-8b29-18ecf9ab0c86.png)

I'm hoping this is just an incorrect classification by the stores... 😕

**Comment by miquelfire** [comment]
#180 

We were talking about this. Someone else resubmitted it to the web store and it has a new URL https://chrome.google.com/webstore/detail/passwordmaker-org/fckpmekmkjglpmdcbfkchimdelcjiipd

Since the person in charge before seems to have disappear, we don't know the exact reason for it to be removed, but it's assumed that some new policy wasn't being followed and it had to be marked as removed. (The new version is 0.9.1, 0.9.0 had a permission that wasn't needed and it was rejected during review)

**Comment by BigBlueHat** [comment]
Makes sense. The store policies keep changing and with little to no notice either... They also aren't good at communicating to communities--just individuals (who, obviously, should be allowed to move on to other things and hand off the reigns to whomever is still interested).

Anyhow...it does make this project hard to trust...which is unfortunate. 😞

I'll check out the newly republished extension.
