### ISSUE TITLE
Site matching fails to use the proper profile

### ISSUE THREAD

**Issue by INeedCaffeine** [passwordmaker/chrome-passwordmaker#186]
I have profiles for both *.aa.com and *.usaa.com. Whenever I go to usaa.com PWM always selects the profile for aa.com.

I tried setting the site names to not include wildcards (e.g. aa.com and www.aa.com VS usaa.com or www.usaa.com) but the mismatch still happens.

I thought it could be an issue with regex's so I tried setting the sites to *(backslash).aa(backslash).com and *(backslash).usaa(backslash).com but the mismatch still happens.  I also tried other expression formats but nothing seems to make PWM properly select the profile for usaa.com when I go to that site; it always selects the aa.com profile.

Is there some secret to making PWM properly match usaa.com with its actual profile or is this a subtle bug in PWM?

Configuration: PasswordMaker (.org) 0.9.1 with Chrome on Windows 10.

Note: The (backslash) above is really the backslash character which GitHub filters out when rendering.

**Comment by heavensrevenge** [comment]
@INeedCaffeine Use www.aa.com in the "Use with sites" field, check the box for "Subdomain(s)" under URL Components, and if desired set "Use This Text" to "aa.com" to remove the www. part.

This is not a bug, but a configuration issue.

**Comment by jeremy-harnois** [comment]
@INeedCaffeine, note that making changes in **URL Components** and **Use This Text** will change the generated password.

@heavensrevenge, I'm not sure this is only a configuration issue. [getAutoProfileIdForUrl()](https://github.com/passwordmaker/chrome-passwordmaker/blob/master/javascript/popup.js#L8-L32) doesn't appear to escape periods, so they're treated as "any one character" by the regex tests. Irrelevant in most cases but, as in this case, it could be an issue with short domains since they're more likely to match longer domains once they're converted to their regular expression.

**Comment by heavensrevenge** [comment]
@INeedCaffeine as of v1.0.1 this is correctly fixed

**Comment by INeedCaffeine** [comment]
@heavensrevenge I just verified it as fixed.  Thanks!!

While trying to log in to reply I noticed something odd.  My profile for GitHub did not match as expected but my test sites usaa.com and aa.com did match their profiles.  

All 3 sites have 2 components in their names, no www or other subdomains.  My profiles all use the pattern *.domain.com (e.g. *.github.com, *.usaa.com, and *.aa.com).  For some reason my GitHub profile does not match but the other 2 do.  Any ideas why what would be?  

The easy workaround is to add just github.com to the GitHub profile but I'd sure like to understand why the behavior is not consistent.

**Comment by heavensrevenge** [comment]
@INeedCaffeine well interestingly github.com has no www. in-front of the url, while usaa.com & aa.com do, so github can't match because there is no www. part in the browser URL which you can check by selecting everything in the URL input bar to see it's entire URI but `http?://github.com` will match or if you want full regex power you can enclose in / /'s `/^http.?:\/\/github\.com/`

Also something new I am doing is short-circuiting the logic for when something is found, before it went through all profiles even after a match was found, now as soon as a match is found it returns the matching profile immediately instead of checking through all the subsequent profiles after it already found a match  It wouldn't affect this but its a nice improvement I added at the same time. So now the first match will return instead of the last match.

**Comment by INeedCaffeine** [comment]
Damn you Chrome!  In the URL bar I see aa.com and usaa.com like I typed.  It isn't until I click on URL to edit it that the www. appear on those sites (but not GitHub obviously).  

To avoid a mismatch on a typo squatted domain (e.g. `**bad-**github.com`) I'll skip trying `*github.com` and go with a second entry for the base domain name for now.  When I have some time to play with regex's I'll revisit my profiles and tidy things up a bit.  

Thanks again.
